export const sports =[
   
    { id: 0, reqName:'CROSSFIT',            value: "Crossfit", isChecked: false ,fav:false},
    { id: 1, reqName:'KITEBOARDING',        value: "Kitesurf", isChecked: false ,fav:false},
    { id: 2, reqName:'MOUNTAIN_BIKING' ,    value: "Vtt",      isChecked: false ,fav:false},
    { id: 3, reqName:'SURFING',             value: "Surf",     isChecked: false ,fav:false},
    { id: 4, reqName:'SKIING',              value: "Ski",     isChecked: false ,fav:false},
    { id: 5, reqName:'HIKING',              value: "Randonée", isChecked: false ,fav:false},
    { id: 6, reqName: 'CLIMBING',           value: "Escalade", isChecked: false ,fav:false},
    { id: 7, reqName: 'CYCLING',            value: "Cyclisme", isChecked: false ,fav:false},
    { id: 8, reqName: 'HORSE_RIDING',       value: "Equitation", isChecked: false ,fav:false},
    { id: 9, reqName: 'WAKEBOARDING',       value: "Wakeboard", isChecked: false ,fav:false},
    { id: 10,reqName: 'MOUNTAINEERING',     value: "Alpinisme", isChecked: false ,fav:false},
    { id: 11,reqName: 'FREE_DIVING',        value: "Apnée", isChecked: false ,fav:false},
    { id: 12,reqName: 'OTHER',              value: "Autre", isChecked: false ,fav:false},
    { id: 13,reqName: 'BASKETBALL',         value: "Basketball", isChecked: false ,fav:false},
    { id: 14,reqName: 'BOATING',            value: "Bateau", isChecked: false ,fav:false},
    { id: 15,reqName: 'WELLNESS',           value: "Bien-etre", isChecked: false ,fav:false},
    { id: 16,reqName: 'BMX',                value: "Bmx", isChecked: false ,fav:false},
    { id: 17,reqName: 'CANOE_KAYAK',        value: "Canoe kayak", isChecked: false ,fav:false},
    { id: 18,reqName: 'CANYONING',          value: "Canyoning", isChecked: false ,fav:false},
    { id: 19,reqName: 'CROSSFIT',           value: "Crossfit", isChecked: false ,fav:false},
    { id: 20,reqName: 'CYCLING',            value: "Cyclisme", isChecked: false ,fav:false},
    { id: 21,reqName: 'DANCING',            value: "Danse", isChecked: false ,fav:false},
    { id: 22,reqName: 'CLIMBING',           value: "Escalade", isChecked: false ,fav:false},
    { id: 23,reqName: 'FITNESS',            value: "Fitness", isChecked: false ,fav:false},
    { id: 24,reqName: 'FOOTBALL',           value: "Football", isChecked: false ,fav:false},
    { id: 25,reqName: 'GOLF',               value: "Golf", isChecked: false ,fav:false},
    { id: 26,reqName: 'HANDBALL',           value: "Handball", isChecked: false ,fav:false},
    { id: 27,reqName: 'JETSKIING',          value: "Jetski", isChecked: false ,fav:false},
    { id: 28,reqName: 'KITEBOARDING',       value: "Kitesurf", isChecked: false ,fav:false},
    { id: 29,reqName: 'SLEDGE',             value: "Luge", isChecked: false ,fav:false},
    { id: 30,reqName: 'NORDIC_WALKING',     value: "Marche nordique", isChecked: false ,fav:false},
    { id: 31,reqName: 'MOTOCROSS',           value: "Motocross", isChecked: false ,fav:false},
    { id: 32,reqName: 'BODYBUILDING',       value: "Musculation", isChecked: false ,fav:false},
    { id: 33,reqName: 'SWIMMING',           value: "Natation", isChecked: false ,fav:false},
    { id: 34,reqName: 'NATURE_WILDLIFE',    value: "Nature & animaux", isChecked: false ,fav:false},
    { id: 35,reqName: 'SKYDIVING',          value: "Parachutisme", isChecked: false ,fav:false},
    { id: 36,reqName: 'PARAGLIDING',        value: "Parapente", isChecked: false ,fav:false},
    { id: 37,reqName: 'DIVING',             value: "Plongée", isChecked: false ,fav:false},
    { id: 38,reqName: 'FISHING',            value: "Péche", isChecked: false ,fav:false},
    { id: 39,reqName: 'QUAD_BIKING',        value: "Quad", isChecked: false ,fav:false},
    { id: 40,reqName: 'RAFTING',            value: "Rafting", isChecked: false ,fav:false},
    { id: 41,reqName: 'HIKING',             value: "Randonée", isChecked: false ,fav:false},
    { id: 42,reqName: 'SNOWSHOEING',        value: "Raquette", isChecked: false ,fav:false},
    { id: 43,reqName: 'ROLLERBLADING',      value: "Roller", isChecked: false ,fav:false},
    { id: 44,reqName: 'RUGBY',              value: "Rugby", isChecked: false ,fav:false},
    { id: 45,reqName: 'RUNNING',            value: "Running", isChecked: false ,fav:false},
    { id: 46,reqName: 'ACTION_SPORT',       value: "Sensations fortes", isChecked: false ,fav:false},
    { id: 47,reqName: 'SKATEBOARDING',      value: "Skateboard", isChecked: false ,fav:false},
    { id: 48,reqName: 'SKIING',             value: "Ski", isChecked: false ,fav:false},
    { id: 49,reqName: 'CROSS_COUNTRY_SKIING',value: "Ski de fond", isChecked: false ,fav:false},
    { id: 50,reqName: 'SKI_TOURING',        value: "Ski de randonnée", isChecked: false ,fav:false},
    { id: 51,reqName: 'WATER_SKIING',       value: "Ski nautique", isChecked: false ,fav:false},
    { id: 52,reqName: 'SLACKLINE',          value: "Slackline", isChecked: false ,fav:false},
    { id: 53,reqName: 'SNOWBOARDING',       value: "Snowboard", isChecked: false ,fav:false},
    { id: 54,reqName: 'AIR_SPORT',          value: "Sport aerien", isChecked: false ,fav:false},
    { id: 55,reqName: 'COMBAT_SPORT',       value: "Sport de combat", isChecked: false ,fav:false},
    { id: 56,reqName: 'ICE_SPORT',          value: "Sport de glace", isChecked: false ,fav:false},
    { id: 57,reqName: 'SHOOTING_SPORT',     value: "Sport de tir", isChecked: false ,fav:false},
    { id: 58,reqName: 'MOTORSPORT_SPORT',   value: "Sport mecanique", isChecked: false ,fav:false},
    { id: 59,reqName: 'CAVING',             value: "Spéléologie", isChecked: false ,fav:false},
    { id: 60,reqName: 'SQUASH',             value: "Squash", isChecked: false ,fav:false},
    { id: 61,reqName: 'STAND_UP_PADDLE',    value: "Stand up paddle", isChecked: false ,fav:false},
    { id: 62,reqName: 'SURFING',            value: "Surf", isChecked: false ,fav:false},
    { id: 63,reqName: 'TENNIS',             value: "Tennis", isChecked: false ,fav:false},
    { id: 64,reqName: 'TRAIL',              value: "Trail", isChecked: false ,fav:false},
    { id: 65,reqName: 'TRIAHLON',           value: "Triathlon", isChecked: false ,fav:false},
    { id: 66,reqName: 'VIA_FERRATA',        value: "Via ferrata", isChecked: false ,fav:false},
    { id: 67,reqName: 'SAILING',            value: "Voile", isChecked: false ,fav:false},
    { id: 68,reqName: 'VOLLEYBALL',         value: "Volleyball", isChecked: false ,fav:false},
    { id: 69,reqName: 'MOUNTAIN_BIKING',    value: "Vtt", isChecked: false ,fav:false},
    { id: 70,reqName: 'WAKEBOARDING',       value: "Wakeboard", isChecked: false ,fav:false},
    { id: 71,reqName: 'WINDSURFING',        value: "Windsurf", isChecked: false ,fav:false},
    { id: 72,reqName: 'WING_FOIL',          value: "Wing foil", isChecked: false ,fav:false},
    { id: 73,reqName: 'WINGSUIT_FLYING',    value: "Wingsuit", isChecked: false ,fav:false},
    { id: 74,reqName: 'YOGA',               value: "Yoga", isChecked: false ,fav:false},
    { id: 75,reqName: 'HORSE_RIDING',       value: "Equitation", isChecked: false ,fav:false}
    
]